# Generated by Django 4.2.16 on 2024-11-26 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_sociallinks_alter_about_about_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallinks',
            options={'verbose_name_plural': 'social links'},
        ),
    ]
